## Data Pre Processing

In [ ]:
import numpy as np
import tensorflow as tf

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import os

dataset_path = os.listdir('dataset')

print (dataset_path)  #what kinds of classes are in this dataset

print("Types of classes labels found: ", len(dataset_path))

In [ ]:
class_labels = []

for item in dataset_path:
 # Get all the file names
 all_classes = os.listdir('dataset' + '/' +item)
 #print(all_classes)

 # Add them to the list
 for room in all_classes:
    class_labels.append((item, str('dataset_path' + '/' +item) + '/' + room))
    #print(class_labels[:5])

In [ ]:
# Build a dataframe        
df = pd.DataFrame(data=class_labels, columns=['Labels', 'image'])
print(df.head())
print(df.tail())

       Labels                                              image
0  Holy basil  dataset_path/Holy basil/00b69b4f9c30558c46dd28...
1  Holy basil  dataset_path/Holy basil/0fc08a283c1c69c2e4f0da...
2  Holy basil  dataset_path/Holy basil/1038c1c87f7b6d1088cd31...
3  Holy basil  dataset_path/Holy basil/1296x728_Holy_Basil_11...
4  Holy basil  dataset_path/Holy basil/13ecc69c669e9b6ae12d73...
          Labels                                              image
148  Sweet basil  dataset_path/Sweet basil/sweet-thai-basil-5c0b...
149  Sweet basil  dataset_path/Sweet basil/sweet-thai-basil-herb...
150  Sweet basil          dataset_path/Sweet basil/thai-basil-2.jpg
151  Sweet basil    dataset_path/Sweet basil/thai-sweet-basil_1.jpg
152  Sweet basil  dataset_path/Sweet basil/Thaisweetbasil_1024x1...


In [ ]:
# Let's check how many samples for each category are present
print("Total number of images in the dataset: ", len(df))

label_count = df['Labels'].value_counts()
print(label_count)

Total number of images in the dataset:  153
Labels
Mint           72
Holy basil     41
Sweet basil    40
Name: count, dtype: int64


In [ ]:
import cv2
path = 'dataset/'
dataset_path = os.listdir('dataset')

im_size = 224

images = []
labels = []

for i in dataset_path:
    data_path = path + str(i)  
    filenames = [i for i in os.listdir(data_path) ]
   
    for f in filenames:
        img = cv2.imread(data_path + '/' + f)
        img = cv2.resize(img, (im_size, im_size))
        images.append(img)
        labels.append(i)

In [ ]:
#This model takes input images of shape (224, 224, 3), and the input data should range [0, 255]. 

images = np.array(images)

images = images.astype('float32') / 255.0
images.shape

(153, 224, 224, 3)

In [ ]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
y=df['Labels'].values
print(y)

y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

['Holy basil' 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil'
 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil'
 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil'
 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil'
 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil'
 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil'
 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil'
 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil' 'Holy basil'
 'Holy basil' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint'
 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint'
 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint'
 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint'
 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint'
 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint'
 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Mint' 'Min

In [ ]:
y=y.reshape(-1,1)

from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('my_ohe', OneHotEncoder(), [0])], remainder='passthrough')
Y = ct.fit_transform(y) #.toarray()
print(Y[:5])
print(Y[35:])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0

In [ ]:
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split


images, Y = shuffle(images, Y, random_state=1)


train_x, test_x, train_y, test_y = train_test_split(images, Y, test_size=0.05, random_state=415)

#inpect the shape of the training and testing.
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(145, 224, 224, 3)
(145, 3)
(8, 224, 224, 3)
(8, 3)


## EfficientNet Implementation

In [ ]:
# from tensorflow.keras import layers
# from tensorflow.keras.applications import EfficientNetB0

from tensorflow.python.keras import layers
from keras_efficientnets import EfficientNetB0

NUM_CLASSES = 3
IMG_SIZE = 224
size = (IMG_SIZE, IMG_SIZE)


inputs = layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3))


# Using model without transfer learning

outputs = EfficientNetB0(include_top=True, weights=None, classes=NUM_CLASSES)(inputs)

ModuleNotFoundError: No module named 'keras_applications'